In [1]:
#1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)


int32


In [2]:
#2.Given a NumPy array 'arr', check if its data type is float64.
import numpy as np
arr = np.array([1.5, 2.6, 3.7], dtype=np.float64)
if arr.dtype == np.float64:
    print("Data type is float64")


Data type is float64


In [3]:
#3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
import numpy as np
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


In [4]:
#4.Convert an existing NumPy array 'arr' of integers to float32 data type.
import numpy as np
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr_float = arr.astype(np.float32)
print(arr_float)


[1. 2. 3. 4. 5.]


In [5]:
#5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
import numpy as np
arr = np.array([1.234567891, 2.345678912, 3.456789123], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1.2345679 2.3456788 3.456789 ]


In [6]:
#6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
import numpy as np
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_attributes(arr))


((2, 3), 6, dtype('int32'))


In [7]:
#7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
import numpy as np
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dimension(arr))


2


In [8]:
#8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
import numpy as np
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3], dtype=np.int32)
print(item_size_info(arr))


(4, 12)


In [9]:
#9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
import numpy as np
def array_strides(arr):
    return arr.strides

arr = np.array([1.5, 2.6, 3.7])
print(array_strides(arr))


(8,)


In [10]:
#10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
import numpy as np
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(shape_stride_relationship(arr))


((2, 3), (12, 4))


In [11]:
#11.Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.
import numpy as np
def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))


[0. 0. 0. 0. 0.]


In [12]:
#12.Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.
import numpy as np
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
#13.Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.
import numpy as np
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(0, 10, 2))


[0 2 4 6 8]


In [14]:
#14.Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive).
import numpy as np
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 10, 5))


[ 0.   2.5  5.   7.5 10. ]


In [15]:
#15.Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size n x n using numpy.eye.
import numpy as np
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#16.Write a function that takes a Python list and converts it into a NumPy array.
import numpy as np
def list_to_array(lst):
    return np.array(lst)

lst = [1, 2, 3, 4, 5]
print(list_to_array(lst))


[1 2 3 4 5]


In [17]:
#17.Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()
print(view_arr)


[1 2 3 4 5]


In [18]:
#18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.
import numpy as np
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
#19.Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])
result = np.concatenate((arr1, arr2), axis=1)
print(result)


[[1 2 5]
 [3 4 6]]


In [20]:
#20.Write a function that vertically stacks multiple NumPy arrays given as a list.
import numpy as np
def stack_arrays_vertically(arrays):
    return np.vstack(arrays)

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.array([5, 6])
print(stack_arrays_vertically([arr1, arr2, arr3]))


[[1 2]
 [3 4]
 [5 6]]


In [21]:
#21.Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
import numpy as np
def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

print(create_range_array(1, 10, 2))


[1 3 5 7 9]


In [22]:
#22.Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
import numpy as np
def generate_spaced_array():
    return np.linspace(0, 1, 10)

print(generate_spaced_array())


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
#23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
import numpy as np
def generate_log_space():
    return np.logspace(0, 3, 5)

print(generate_log_space())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
#24.Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import numpy as np
import pandas as pd
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)


    A   B   C
0  87  20   2
1  94  53  81
2  36  23  11
3  67  84  60
4  73  87   9


In [25]:
#25.Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
import pandas as pd
import numpy as np
def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

df = pd.DataFrame({'A': [1, -2, 3, -4, 5]})
print(replace_negatives(df, 'A'))


   A
0  1
1  0
2  3
3  0
4  5


In [26]:
#26.Access the 3rd element from the given NumPy array.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])


30


In [27]:
#27.Retrieve the element at index (1, 2) from the 2D NumPy array.
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])


6


In [28]:
#28.Using boolean indexing, extract elements greater than 5 from the given NumPy array.
import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]
print(result)


[ 8 10  7]


In [29]:
#29.Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])


[3 4 5 6]


In [30]:
#30.Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)


[[2 3]
 [5 6]]


In [31]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [2, 0]])
result = arr_2d[indices]
print(result)


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [32]:
#32.Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
import numpy as np
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 5, 8, 12, 15])
print(filter_greater_than(arr, 8))


[12 15]


In [33]:
#33.Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
import numpy as np
def extract_elements_3d(arr, indices_x, indices_y, indices_z):
    return arr[indices_x, indices_y, indices_z]

arr_3d = np.random.randint(1, 100, (4, 4, 4))
x = np.array([0, 1, 2])
y = np.array([1, 2, 3])
z = np.array([2, 1, 0])
print(extract_elements_3d(arr_3d, x, y, z))


[20 85 78]


In [34]:
#34.Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np
def filter_with_conditions(arr):
    return arr[(arr > 10) & (arr < 50)]

arr = np.array([5, 15, 25, 35, 45, 55])
print(filter_with_conditions(arr))


[15 25 35 45]


In [35]:
#35.Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
import numpy as np
def extract_elements_2d(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 1, 2])
cols = np.array([1, 2, 0])
print(extract_elements_2d(arr_2d, rows, cols))


[2 6 7]


In [36]:
#36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr += 5
print(arr)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
#37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
import numpy as np
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
result = arr1.T * arr2
print(result)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [38]:
#38.Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
result = arr2 + arr1.reshape(-1, 1)
print(result)


[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [39]:
#39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
import numpy as np
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [40]:
#40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])
# Adjust the shapes to be compatible for broadcasting
arr2 = np.hstack([arr2, np.zeros((2, 1))])
result = arr1 * arr2
print(result)



[[ 7. 16.  0.]
 [36. 50.  0.]]


In [41]:
#41.Calculate the column-wise mean for the given array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis=0))


[2.5 3.5 4.5]


In [42]:
#42.Find the maximum value in each row of the given array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr, axis=1))


[3 6]


In [43]:
#43.For the given array, find the indices of the maximum value in each column:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(arr, axis=0))


[1 1 1]


In [44]:
#44.For the given array, apply a custom function to calculate the moving sum along rows:
import numpy as np
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(moving_sum(arr))


[[ 1  3  6]
 [ 4  9 15]]


In [45]:
#45.In the given array, check if all elements in each column are even:
import numpy as np
arr = np.array([[2, 4, 6], [3, 5, 7]])
print(np.all(arr % 2 == 0, axis=0))


[False False False]


In [46]:
#46.Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix:
import numpy as np
def reshape_array(arr, m, n):
    return arr.reshape(m, n)

arr = np.array([1, 2, 3, 4, 5, 6])
print(reshape_array(arr, 2, 3))


[[1 2 3]
 [4 5 6]]


In [47]:
#47.Create a function that takes a matrix as input and returns the flattened array:
import numpy as np
def flatten_matrix(matrix):
    return matrix.flatten()

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(flatten_matrix(matrix))


[1 2 3 4 5 6]


In [48]:
#48.Write a function that concatenates two given arrays along a specified axis:
import numpy as np
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=1))


[[1 2 5 6]
 [3 4 7 8]]


In [49]:
#49.Create a function that splits an array into multiple sub-arrays along a specified axis:
import numpy as np
def split_array(arr, sections, axis):
    return np.array_split(arr, sections, axis=axis)

arr = np.array([[1, 2], [3, 4], [5, 6]])
print(split_array(arr, 2, axis=0))


[array([[1, 2],
       [3, 4]]), array([[5, 6]])]


In [50]:
#50.Write a function that inserts and then deletes elements from a given array at specified indices:
import numpy as np
def insert_and_delete(arr, indices_to_insert, values_to_insert, indices_to_delete):
    arr = np.insert(arr, indices_to_insert, values_to_insert)
    arr = np.delete(arr, indices_to_delete)
    return arr

arr = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
print(insert_and_delete(arr, indices_to_insert, values_to_insert, indices_to_delete))


[ 1 10  4 11  5]


In [51]:
#51.Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2:
import numpy as np
arr1 = np.random.randint(1, 10, size=10)
arr2 = np.arange(1, 11)
print(arr1 + arr2)


[10  3 10  8 13 13 16 10 14 11]


In [52]:
#52.Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise:
import numpy as np
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
print(arr1 - arr2)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [53]:
#53.Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2:
import numpy as np
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
print(arr1 * arr2)


[ 7 10  6  8 20]


In [54]:
#54.Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2:
import numpy as np
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
print(arr1 / arr2)


[2. 2. 2. 2. 2.]


In [55]:
#55.Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise:
import numpy as np
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
print(arr1 ** arr2)


[ 1 16 27 16  5]


In [56]:
#56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings:
import numpy as np
def count_substring(arr, substring):
    return np.char.count(arr, substring)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print(count_substring(arr, 'hello'))


[1 0 1 0 1]


In [57]:
#57.Write a function that extracts uppercase characters from a NumPy array of strings:
import numpy as np
def extract_uppercase(arr):
    return np.char.upper(arr)

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print(extract_uppercase(arr))


['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [58]:
#58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string:
import numpy as np
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(replace_substring(arr, 'apple', 'orange'))


['orange' 'banana' 'grape' 'pineorange']


In [59]:
#59.Write a function that concatenates strings in a NumPy array element-wise:
import numpy as np
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print(concatenate_strings(arr1, arr2))


['HelloOpen' 'WorldAI']


In [60]:
#60.Write a function that finds the length of the longest string in a NumPy array:
import numpy as np
def longest_string(arr):
    return max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string(arr))


9


In [61]:
#61.Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions:
import numpy as np
arr = np.random.randint(1, 1001, size=100)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std_dev = np.std(arr)
print(mean, median, variance, std_dev)


482.63 465.0 87529.1131 295.8531951830164


In [62]:
#62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset:
import numpy as np
arr = np.random.randint(1, 101, size=50)
p25 = np.percentile(arr, 25)
p75 = np.percentile(arr, 75)
print(p25, p75)


24.25 72.25


In [63]:
#63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function:
import numpy as np
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)
correlation = np.corrcoef(arr1, arr2)
print(correlation)


[[1.         0.22031469]
 [0.22031469 1.        ]]


In [64]:
#64.Create two matrices and perform matrix multiplication using NumPy's dot function:
import numpy as np
mat1 = np.random.randint(1, 10, (3, 2))
mat2 = np.random.randint(1, 10, (2, 3))
result = np.dot(mat1, mat2)
print(result)


[[50 40 69]
 [74 28 47]
 [74 28 47]]


In [65]:
#65.Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles:
import numpy as np
arr = np.random.randint(10, 1001, size=50)
p10 = np.percentile(arr, 10)
p50 = np.median(arr)
p90 = np.percentile(arr, 90)
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)
print(p10, p50, p90, q1, q3)


176.3 448.5 898.1 276.0 760.5


In [66]:
#66.Create a NumPy array of integers and find the index of a specific element:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
index = np.where(arr == 3)
print(index)


(array([2], dtype=int64),)


In [67]:
#67.Generate a random NumPy array and sort it in ascending order:
import numpy as np
arr = np.random.randint(1, 101, size=10)
arr_sorted = np.sort(arr)
print(arr_sorted)


[ 2  7  8 13 15 15 17 44 53 86]


In [68]:
#68.Filter elements greater than 20 in the given NumPy array:
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])
result = arr[arr > 20]
print(result)


[25 42 30]


In [69]:
#69.Filter elements which are divisible by 3 from a given NumPy array:
import numpy as np
arr = np.array([1, 5, 8, 12, 15])
result = arr[arr % 3 == 0]
print(result)


[12 15]


In [70]:
#70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
result = arr[(arr >= 20) & (arr <= 40)]
print(result)


[20 30 40]


In [71]:
#71.For the given NumPy array, check its byte order using the dtype attribute byteorder:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype.byteorder)


=


In [72]:
#72.For the given NumPy array, perform byte swapping in place using byteswap():
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)
print(arr)


[16777216 33554432 50331648]


In [73]:
#73.For the given NumPy array, swap its byte order without modifying the original array using newbyteorder():
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.newbyteorder()
print(new_arr)


[16777216 33554432 50331648]


In [74]:
#74.For the given NumPy array, swap its byte order conditionally based on system endianness using newbyteorder():
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':  # '=' indicates native endianness
    arr = arr.newbyteorder()
print(arr)


[16777216 33554432 50331648]


In [75]:
#75.For the given NumPy array, check if byte swapping is necessary for the current system using dtype attribute byteorder:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
needs_swap = arr.dtype.byteorder not in ('=', '|')
print(needs_swap)


False


In [76]:
#76.Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1:
import numpy as np
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 99
print(arr1)
print(copy_arr)


[ 1  2  3  4  5  6  7  8  9 10]
[99  2  3  4  5  6  7  8  9 10]


In [77]:
#77.Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix:
import numpy as np
matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 99
print(matrix)


[[99  5  3]
 [ 9  8  7]
 [ 1  1  9]]


In [78]:
#78.Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a:
import numpy as np
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
print(array_a)


[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


In [79]:
#79.Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it reflects changes in the original orig_array:
import numpy as np
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99
print(orig_array)


[[99  2  3  4]
 [ 5  6  7  8]]


In [80]:
#80.Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data:
import numpy as np
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 99
print(data)


[[6 1 9 7]
 [8 2 9 9]
 [5 7 2 3]]


In [81]:
#81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them:
import numpy as np
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))
print(A + B)
print(A - B)


[[ 2 14 12]
 [ 8  8  9]
 [11 12  3]]
[[ 0 -4  2]
 [ 4 -2  5]
 [-5  0  1]]


In [82]:
#82.Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication:
import numpy as np
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))
print(np.dot(C, D))


[[ 33  67  80  62]
 [  9  19  22  17]
 [ 51  89 120  94]]


In [83]:
#83.Create a matrix E and find its transpose:
import numpy as np
E = np.random.randint(1, 10, size=(3, 3))
print(E.T)


[[9 7 5]
 [3 2 7]
 [1 3 7]]


In [84]:
#84.Generate a square matrix F and compute its determinant:
import numpy as np
F = np.random.randint(1, 10, size=(3, 3))
det = np.linalg.det(F)
print(det)


-96.00000000000007


In [85]:
#85.Create a square matrix G and find its inverse:
import numpy as np
G = np.random.randint(1, 10, size=(3, 3))
inverse_G = np.linalg.inv(G)
print(inverse_G)


[[-0.37864078  0.16504854  0.19417476]
 [ 0.17475728  0.0776699  -0.32038835]
 [ 0.09708738 -0.06796117  0.15533981]]
